source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform:ios,'7.0'
target 'DouDouStopCar' do
    pod 'AFNetworking','~> 3.0'
    pod 'MJExtension'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'FMDB'
    pod 'Reachability'
    pod 'IQKeyboardManager'
    pod 'RDVTabBarController'
    pod 'FDFullscreenPopGesture', '~> 1.1'
    pod 'JVFloatLabeledTextField'
    pod 'SDWebImage', '~> 3.7'
    pod 'Masonry'
    pod 'DZNEmptyDataSet'#空数据源
end
